name: dnscrypt-proxy
services:
  dnscrypt-proxy:
    build:
      context: "."
      dockerfile: Dockerfile
      tags:
        - ghcr.io/p1ratrulezzz/dnscrypt-proxy:latest
    #command:
    #  - tail -f /dev/null
    x-bake:
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      pull: false